# Generated by Django 4.1.2 on 2022-11-15 00:45

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=150)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=150)),
                ('nome', models.CharField(max_length=150)),
                ('produto_imagem', models.ImageField(blank=True, null=True, upload_to=core.models.get_file_path)),
                ('quantidade', models.IntegerField()),
                ('descricao', models.CharField(max_length=250)),
                ('valorcompra', models.FloatField()),
                ('valorvenda', models.FloatField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
