# Generated by Django 4.1.2 on 2022-11-12 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='itempadr',
            name='pedidos',
        ),
        migrations.RemoveField(
            model_name='itempadr',
            name='preferencias',
        ),
        migrations.AddField(
            model_name='pedido',
            name='item',
            field=models.ManyToManyField(to='core.itempadr'),
        ),
        migrations.AddField(
            model_name='itempadr',
            name='tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.tipoitem'),
        ),
    ]
