# Generated by Django 4.1.2 on 2022-10-09 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupcake',
            name='price',
            field=models.DecimalField(
                decimal_places=2, default=0.00, max_digits=10),  # type: ignore
        ),
    ]
