# Generated by Django 4.1.2 on 2022-10-15 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_cupcake_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cupcake',
            new_name='ItemPadr',
        ),
    ]
