# Generated by Django 4.1.2 on 2022-11-12 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tipoitem_remove_itempadr_pedidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='item',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos', to='core.itempadr'),
        ),
    ]
