# Generated by Django 4.1.2 on 2022-11-12 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pedido_item_pedido_itens'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itempadr',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.RemoveField(
            model_name='itempadr',
            name='inventory',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itemnumber',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='totalprice',
        ),
        migrations.CreateModel(
            name='ItensPedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.itempadr')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pedido')),
            ],
            options={
                'unique_together': {('pedido', 'item')},
            },
        ),
    ]
