# Generated by Django 4.1.2 on 2022-10-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_cupcake_itempadr'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempadr',
            name='inventory',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
