# Generated by Django 4.1.2 on 2022-11-12 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_price_itempadr_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
